name = "Acme-Onion"
badges = ["github-actions/test.yml", "metacpan"]
authority="cpan:KFLY"

module_maker="ModuleBuildTiny"
static_install = "auto"
markdown_maker = "Pod::Markdown::Github"

[release]
branch='main'
